# Generated by Django 5.2.1 on 2025-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Укажите ФИО",
                        max_length=100,
                        verbose_name="ФИО"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите должность",
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Укажите почту",
                        max_length=254,
                        null=True,
                        verbose_name="Почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
