# Generated by Django 5.2.1 on 2025-05-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
