# Generated by Django 5.2.1 on 2025-05-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название задачи",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание задачи",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершена"),
                        ],
                        default="new",
                        help_text="Укажите статус задачи",
                        max_length=20,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="Укажите срок выполнения задачи", verbose_name="Срок"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="Укажите приоритет задачи",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите сотрудника, которому назначена задача",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="employees.employee",
                        verbose_name="Назначен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
