# Generated by Django 5.2.1 on 2025-05-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, создавший задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите родительскую задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_tasks",
                to="tasks.task",
                verbose_name="Родительская задача",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, обновивший задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновил",
            ),
        ),
    ]
