# Generated by Django 5.2.1 on 2025-05-28 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(
                default=datetime.date(2025, 5, 28),
                help_text="Укажите срок выполнения задачи",
                verbose_name="Срок",
            ),
        ),
    ]
